# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=31),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='relationship',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=31),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='street_address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='street_address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='zip_code',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=31),
        ),
        migrations.AlterField(
            model_name='user',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=31),
        ),
        migrations.AlterField(
            model_name='user',
            name='street_address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='street_address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='zip_code',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='lic_plate_num',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='lic_plate_st',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=63),
        ),
    ]
