# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailhead_latitude', models.CharField(max_length=20)),
                ('trailhead_longitude', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
            ],
        ),
    ]
