# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20171001_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(choices=[('ST', 'Start Location'), ('EN', 'End Location'), ('OB', 'Objective Location'), ('CM', 'Camp Location')], max_length=2)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(blank=True)),
                ('latitude', models.CharField(blank=True, max_length=31)),
                ('longitude', models.CharField(blank=True, max_length=31)),
            ],
        ),
        migrations.RemoveField(
            model_name='suntime',
            name='trailhead_latitude',
        ),
        migrations.RemoveField(
            model_name='suntime',
            name='trailhead_longitude',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trailhead_latitude',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trailhead_longitude',
        ),
        migrations.AddField(
            model_name='suntime',
            name='latitude',
            field=models.CharField(blank=True, max_length=31),
        ),
        migrations.AddField(
            model_name='suntime',
            name='longitude',
            field=models.CharField(blank=True, max_length=31),
        ),
        migrations.AddField(
            model_name='triplocation',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.Trip'),
        ),
    ]
