# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20170828_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='th_lat',
            new_name='trailhead_latitude',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='th_lon',
            new_name='trailhead_longitude',
        ),
    ]
