# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20171002_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triplocation',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
