# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20171004_1029'),
    ]

    operations = [
        migrations.AlterField('TripLocation', 'date', models.CharField(default='Unassigned', max_length=255, blank=True, null=True))
    ]
