# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_auto_20170831_0804'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
