# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_auto_20171009_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triplocation',
            name='date',
            field=models.CharField(default='Unassigned', max_length=255),
        ),
    ]
