# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_auto_20171009_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='destination',
        ),
    ]
