# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_tripmember_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripmember',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
