# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_itemnotification_tripnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripnotification',
            name='member',
        ),
        migrations.RemoveField(
            model_name='tripnotification',
            name='trip',
        ),
        migrations.DeleteModel(
            name='TripNotification',
        ),
    ]
