# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_auto_20171025_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triplocation',
            name='location_type',
            field=models.CharField(choices=[('ST', 'Trailhead'), ('EN', 'Endpoint'), ('OB', 'Objective'), ('CM', 'Camp')], max_length=2),
        ),
    ]
