# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-30 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0015_auto_20171212_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suntime',
            name='trip',
        ),
        migrations.AddField(
            model_name='triplocation',
            name='dawn',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='triplocation',
            name='dusk',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='triplocation',
            name='sunrise',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='triplocation',
            name='sunset',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SunTime',
        ),
    ]
