# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('th_lat', models.CharField(max_length=20)),
                ('th_lon', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='trips',
            field=models.ManyToManyField(to='trips.Trip'),
        ),
    ]
