# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_trip_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='trips',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
